In [41]:
import pandas as pd
df=pd.read_csv(r"C:\Users\ravin\OneDrive\Desktop\git\vizag_hpp.csv")
df

location  total_sqft  bath  bhk  price_per_sqft      price
0    Achiyammapeta      1750.0   1.0  2.0          2900.0  5075000.0
1    Achiyammapeta      1565.0   2.0  2.0          2900.0  4538500.0
2    Achiyammapeta      1250.0   2.0  2.0          2900.0  3625000.0
3    Achiyammapeta      1000.0   2.0  3.0          2900.0  2900000.0
4    Achiyammapeta       750.0   1.0  2.0          2900.0  2175000.0
..             ...         ...   ...  ...             ...        ...
863            NaN         NaN   NaN  NaN             NaN        NaN
864            NaN         NaN   NaN  NaN             NaN        NaN
865            NaN         NaN   NaN  NaN             NaN        NaN
866            NaN         NaN   NaN  NaN             NaN        NaN
867            NaN         NaN   NaN  NaN             NaN        NaN

[868 rows x 6 columns]

In [42]:
df.tail(10)

location  total_sqft  bath  bhk  \
858  Zilla Grandalayam Area Mandapem Area      1000.0   1.0  2.0   
859  Zilla Grandalayam Area Mandapem Area       750.0   1.0  1.0   
860                                   NaN         NaN   NaN  NaN   
861                                   NaN         NaN   NaN  NaN   
862                                   NaN         NaN   NaN  NaN   
863                                   NaN         NaN   NaN  NaN   
864                                   NaN         NaN   NaN  NaN   
865                                   NaN         NaN   NaN  NaN   
866                                   NaN         NaN   NaN  NaN   
867                                   NaN         NaN   NaN  NaN   

     price_per_sqft      price  
858          3900.0  3900000.0  
859          3900.0  2925000.0  
860             NaN        NaN  
861             NaN        NaN  
862             NaN        NaN  
863             NaN        NaN  
864             NaN        NaN  
865             NaN        NaN  
866             NaN        NaN  
867             NaN        NaN

In [43]:
df.shape

(868, 6)

In [44]:
df.isnull().sum()

location          8
total_sqft        8
bath              8
bhk               8
price_per_sqft    8
price             8
dtype: int64

In [45]:
df.isnull().sum().sum()

48

In [47]:
df1=df.dropna()
df1.tail(10)

location  total_sqft  bath  bhk  \
850                      YSR Stadium Road      1750.0   2.0  3.0   
851                      YSR Stadium Road      1565.0   1.0  2.0   
852                      YSR Stadium Road      1250.0   2.0  2.0   
853                      YSR Stadium Road      1000.0   1.0  2.0   
854                      YSR Stadium Road       750.0   2.0  3.0   
855  Zilla Grandalayam Area Mandapem Area      1750.0   2.0  3.0   
856  Zilla Grandalayam Area Mandapem Area      1565.0   2.0  2.0   
857  Zilla Grandalayam Area Mandapem Area      1250.0   2.0  2.0   
858  Zilla Grandalayam Area Mandapem Area      1000.0   1.0  2.0   
859  Zilla Grandalayam Area Mandapem Area       750.0   1.0  1.0   

     price_per_sqft      price  
850          4700.0  8225000.0  
851          4700.0  7355500.0  
852          4700.0  5875000.0  
853          4700.0  4700000.0  
854          4700.0  3525000.0  
855          3900.0  6825000.0  
856          3900.0  6103500.0  
857          3900.0  4875000.0  
858          3900.0  3900000.0  
859          3900.0  2925000.0

In [48]:
df1.price_per_sqft.describe()

count     860.000000
mean     4218.720930
std      1134.540053
min      2100.000000
25%      3200.000000
50%      4300.000000
75%      4850.000000
max      6500.000000
Name: price_per_sqft, dtype: float64

In [50]:
df2=df1.drop(['price_per_sqft'],axis='columns')

In [52]:
dummies=pd.get_dummies(df2.location)
dummies

ASR statue Steel plant Staff Quarters  \
0                                    False   
1                                    False   
2                                    False   
3                                    False   
4                                    False   
..                                     ...   
855                                  False   
856                                  False   
857                                  False   
858                                  False   
859                                  False   

     AU Distance Education Centre Kirlampudi Layout  AU Outgate  \
0                                             False       False   
1                                             False       False   
2                                             False       False   
3                                             False       False   
4                                             False       False   
..                                              ...         ...   
855                                           False       False   
856                                           False       False   
857                                           False       False   
858                                           False       False   
859                                           False       False   

     AU Quarters Sirupuram  AVN College road  Achiyammapeta  Adarsh Nagar  \
0                    False             False           True         False   
1                    False             False           True         False   
2                    False             False           True         False   
3                    False             False           True         False   
4                    False             False           True         False   
..                     ...               ...            ...           ...   
855                  False             False          False         False   
856                  False             False          False         False   
857                  False             False          False         False   
858                  False             False          False         False   
859                  False             False          False         False   

     Akkayyapalem  Allipuram  Allipuram Bazzar  ...  VUDA HSBC Area  \
0           False      False             False  ...           False   
1           False      False             False  ...           False   
2           False      False             False  ...           False   
3           False      False             False  ...           False   
4           False      False             False  ...           False   
..            ...        ...               ...  ...             ...   
855         False      False             False  ...           False   
856         False      False             False  ...           False   
857         False      False             False  ...           False   
858         False      False             False  ...           False   
859         False      False             False  ...           False   

     Visalakshi Nagar  VizianagaramPalaceLayout  Waltair Main Road  \
0               False                     False              False   
1               False                     False              False   
2               False                     False              False   
3               False                     False              False   
4               False                     False              False   
..                ...                       ...                ...   
855             False                     False              False   
856             False                     False              False   
857             False                     False              False   
858             False                     False              False   
859             False                     False              False   

     YSR Stadium Road  Yedug

In [53]:
dummies = dummies.astype(int)
dummies.head(3)

ASR statue Steel plant Staff Quarters  \
0                                      0   
1                                      0   
2                                      0   

   AU Distance Education Centre Kirlampudi Layout  AU Outgate  \
0                                               0           0   
1                                               0           0   
2                                               0           0   

   AU Quarters Sirupuram  AVN College road  Achiyammapeta  Adarsh Nagar  \
0                      0                 0              1             0   
1                      0                 0              1             0   
2                      0                 0              1             0   

   Akkayyapalem  Allipuram  Allipuram Bazzar  ...  VUDA HSBC Area  \
0             0          0                 0  ...               0   
1             0          0                 0  ...               0   
2             0          0                 0  ...               0   

   Visalakshi Nagar  VizianagaramPalaceLayout  Waltair Main Road  \
0                 0                         0                  0   
1                 0                         0                  0   
2                 0                         0                  0   

   YSR Stadium Road  Yedugulla road  Yellemma Thota Suryabagh Area  Yendada  \
0                 0               0                              0        0   
1                 0               0                              0        0   
2                 0               0                              0        0   

   Yethapeta Road Allipuram  Zilla Grandalayam Area Mandapem Area  
0                         0                                     0  
1                         0                                     0  
2                         0                                     0  

[3 rows x 172 columns]

In [54]:
df2=pd.concat([df2,dummies],axis=1)
df2.tail(3)

location  total_sqft  bath  bhk      price  \
857  Zilla Grandalayam Area Mandapem Area      1250.0   2.0  2.0  4875000.0   
858  Zilla Grandalayam Area Mandapem Area      1000.0   1.0  2.0  3900000.0   
859  Zilla Grandalayam Area Mandapem Area       750.0   1.0  1.0  2925000.0   

     ASR statue Steel plant Staff Quarters  \
857                                      0   
858                                      0   
859                                      0   

     AU Distance Education Centre Kirlampudi Layout  AU Outgate  \
857                                               0           0   
858                                               0           0   
859                                               0           0   

     AU Quarters Sirupuram  AVN College road  ...  VUDA HSBC Area  \
857                      0                 0  ...               0   
858                      0                 0  ...               0   
859                      0                 0  ...               0   

     Visalakshi Nagar  VizianagaramPalaceLayout  Waltair Main Road  \
857                 0                         0                  0   
858                 0                         0                  0   
859                 0                         0                  0   

     YSR Stadium Road  Yedugulla road  Yellemma Thota Suryabagh Area  Yendada  \
857                 0               0                              0        0   
858                 0               0                              0        0   
859                 0               0                              0        0   

     Yethapeta Road Allipuram  Zilla Grandalayam Area Mandapem Area  
857                         0                                     1  
858                         0                                     1  
859                         0                                     1  

[3 rows x 177 columns]

In [57]:
df3=df2.drop(['location'],axis=1)
df3

total_sqft  bath  bhk      price  ASR statue Steel plant Staff Quarters  \
0        1750.0   1.0  2.0  5075000.0                                      0   
1        1565.0   2.0  2.0  4538500.0                                      0   
2        1250.0   2.0  2.0  3625000.0                                      0   
3        1000.0   2.0  3.0  2900000.0                                      0   
4         750.0   1.0  2.0  2175000.0                                      0   
..          ...   ...  ...        ...                                    ...   
855      1750.0   2.0  3.0  6825000.0                                      0   
856      1565.0   2.0  2.0  6103500.0                                      0   
857      1250.0   2.0  2.0  4875000.0                                      0   
858      1000.0   1.0  2.0  3900000.0                                      0   
859       750.0   1.0  1.0  2925000.0                                      0   

     AU Distance Education Centre Kirlampudi Layout  AU Outgate  \
0                                                 0           0   
1                                                 0           0   
2                                                 0           0   
3                                                 0           0   
4                                                 0           0   
..                                              ...         ...   
855                                               0           0   
856                                               0           0   
857                                               0           0   
858                                               0           0   
859                                               0           0   

     AU Quarters Sirupuram  AVN College road  Achiyammapeta  ...  \
0                        0                 0              1  ...   
1                        0                 0              1  ...   
2                        0                 0              1  ...   
3                        0                 0              1  ...   
4                        0                 0              1  ...   
..                     ...               ...            ...  ...   
855                      0                 0              0  ...   
856                      0                 0              0  ...   
857                      0                 0              0  ...   
858                      0                 0              0  ...   
859                      0                 0              0  ...   

     VUDA HSBC Area  Visalakshi Nagar  VizianagaramPalaceLayout  \
0                 0                 0                         0   
1                 0                 0                         0   
2                 0                 0                         0   
3                 0                 0                         0   
4                 0                 0                         0   
..              ...               ...                       ...   
855               0                 0                         0   
856               0                 0                         0   
857               0                 0                         0   
858               0                 0                         0   
859               0                 0                         0   

     Waltair Main Road  YSR Stadium Road  Yedugulla road  \
0                    0                 0               0   
1                    0                 0               0   
2                    0                 0               0   
3                    0                 0               0   
4                    0                 0               0   
..                 ...               ...             ...   
855                  0                 0               0   
856                  0                 0               0   
857                  0                 0               0   
858              

In [58]:
df3=df3.copy()

In [59]:
x=df3.drop('price',axis=1)
y=df3.price
print(x.head(3))
print(y.head(3))

   total_sqft  bath  bhk  ASR statue Steel plant Staff Quarters  \
0      1750.0   1.0  2.0                                      0   
1      1565.0   2.0  2.0                                      0   
2      1250.0   2.0  2.0                                      0   

   AU Distance Education Centre Kirlampudi Layout  AU Outgate  \
0                                               0           0   
1                                               0           0   
2                                               0           0   

   AU Quarters Sirupuram  AVN College road  Achiyammapeta  Adarsh Nagar  ...  \
0                      0                 0              1             0  ...   
1                      0                 0              1             0  ...   
2                      0                 0              1             0  ...   

   VUDA HSBC Area  Visalakshi Nagar  VizianagaramPalaceLayout  \
0               0                 0                         0   
1               0  

In [60]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2, random_state=143)
model=LinearRegression()
model.fit(x_train,y_train)
model.score(x_train,y_train)

0.9665434331088607

In [61]:
from sklearn.model_selection import ShuffleSplit
from sklearn.model_selection import cross_val_score
crs_val=ShuffleSplit(n_splits=5, test_size=0.2, random_state= 114433)
cross_val_score(LinearRegression(), x, y, cv=crs_val)

array([0.9338544 , 0.94013829, 0.94564189, 0.94146353, 0.94322659])

In [62]:
from sklearn.model_selection import GridSearchCV

from sklearn.linear_model import Lasso
from sklearn.tree import DecisionTreeRegressor

def find_best_model_using_gridsearchcv(x,y):
    algos = {
        'linear_regression' : {
            'model': LinearRegression(),
            'params': {
                'copy_X': [True, False],
                'fit_intercept': [True, False],
                'n_jobs': [None, 1, 2, 3],  # Adjust the number of jobs as needed
                'positive': [False]
            }
        },
        'lasso': {
            'model': Lasso(),
            'params': {
                'alpha': [1,2],
                'selection': ['random', 'cyclic']
            }
        },
        'decision_tree': {
            'model': DecisionTreeRegressor(),
            'params': {
                'criterion': ['mse', 'friedman_mse'],
                'splitter': ['best', 'random']
            }
        }
    }

    scores = []

    crs_val = ShuffleSplit(n_splits=5, test_size=0.2, random_state=114433)

    for algo_name, algo in algos.items():
        gscv = GridSearchCV(algo['model'], algo['params'], cv=crs_val, return_train_score=False)
        gscv.fit(x, y)
        scores.append({
            'algorithm': algo_name,
            'best_paramts': gscv.best_params_,
            'best_score': gscv.best_score_
        })

    return pd.DataFrame(scores,columns=['algorithm','best_score','best_paramts'])
find_best_model_using_gridsearchcv(x,y)

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.637e+13, tolerance: 3.492e+11
  model = cd_fast.enet_coordinate_descent(
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.669e+13, tolerance: 3.516e+11
  model = cd_fast.enet_coordinate_descent(
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.027e+13, toleranc

algorithm  best_score  \
0  linear_regression    0.940865   
1              lasso    0.940867   
2      decision_tree   -0.057359   

                                        best_paramts  
0  {'copy_X': True, 'fit_intercept': True, 'n_job...  
1                {'alpha': 2, 'selection': 'cyclic'}  
2  {'criterion': 'friedman_mse', 'splitter': 'ran...

In [104]:
def predict_price(location,sqft,bath,bhk):
    loc_index = np.where(x.columns==location)[0][0]
    p=np.zeros(len(x.columns))
    p[0]=sqft
    p[1]=bhk
    p[2]=bath
    if loc_index>=0:
        p[loc_index]=1
    return model.predict([p])[0]  ##X has 3 features, but LinearRegression is expecting 175 features as input.(dee down predict method)

In [105]:
print(predict_price('Achiyammapeta', 1000, 3, 4))

2404612.5596473063


C:\ProgramData\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


In [76]:
arr = np.array([12, 2, 3, 4, 5])
indices = np.where(arr > 3)
print(indices)

(array([0, 3, 4], dtype=int64),)


In [78]:
arr = np.array([12, 2, 3, 4, 5])
indices = np.where(arr > 3)[0]
print(indices)

[0 3 4]


In [79]:
arr = np.array([12, 2, 3, 4, 5])
indices = np.where(arr > 3)[0][0]
print(indices)

0


In [87]:
arr = np.array([[12,2,3], [ 4,5,0]])
indices = np.where(arr > 3)
print(indices)

(array([0, 1, 1], dtype=int64), array([0, 0, 1], dtype=int64))


In [88]:
arr = np.array([[12,2,3], [ 4,5,0]])
indices = np.where(arr > 3)[0]
print(indices)

[0 1 1]


In [89]:
arr = np.array([[12,2,3], [ 4,5,0]])
indices = np.where(arr > 3)[0][0]
print(indices)

0


In [90]:
arr = np.array([[12,2,3], [ 4,5,0]])
indices = np.where(arr > 13)[0][0]   
print(indices)

IndexError: index 0 is out of bounds for axis 0 with size 0

In [93]:
model.predict([[12,2,3], [ 4,5,0]]) ###X has 3 features, but LinearRegression is expecting 175 features as input.(see down)


C:\ProgramData\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


ValueError: X has 3 features, but LinearRegression is expecting 175 features as input.

In [99]:
loc_index = np.where(x.columns=="Achiyammapeta")[0][0]
loc_index

8

In [100]:
loc_index = np.where(x.columns=="Achiyammapeta")[0]
loc_index

array([8], dtype=int64)

In [101]:
loc_index = np.where(x.columns=="Achiyammapeta")
loc_index

(array([8], dtype=int64),)

In [106]:
import pickle
with open('vsp.pikl','wb') as f:
    pickle.dump(model,f)

In [107]:
import json
columns={
    'data_columns':[col.lower() for col in x.columns]
}
with open("columns_vsp.json","w") as f:
    f.write(json.dumps(columns))